#-----------------------------------
--- # Application
#-----------------------------------
spring:
  application:
    name: thesis-webrepo
server:
  port: 8080
  servlet:
    context-path: /api

#-----------------------------------
--- # Database
#-----------------------------------
spring:
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: false

# --- # PostgreSQL
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: validate
#   ## Datasource
#   datasource:
#     url: jdbc:postgresql://localhost:5432/webrepo
#     username: 's53kr_lm8a6r'
#     password: '$p@s5w0rD_s53k12x'

--- # H2 In-Memory
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  ## Datasource
  datasource:
    url: jdbc:h2:mem:testdb
    username: 's53kr_lm8a6r'
    password: '$p@s5w0rD_s53k12x'

#-----------------------------------
--- # Security
#-----------------------------------
application:
  security:
    # DEFINE ROUNDS OF VALIDATION
    # TO STRENGTHEN PASSWORD PROCESSING
    strength: 8
    # DEFAULT LOGIN CREDENTIALS
    # WITH ROLE OF SYSTEM ADMIN
    default-login-enabled: true
    default-login: sysadm
    default-password: sysadm

#-----------------------------------
--- # File Storage --- MinIO
#-----------------------------------

application:
  minio:
    url: http://127.0.0.1:9000
    username: s53kr_lm8a6r
    password: $p@s5w0rD_s53k12x
    get-error-message: SYSTEM.ERROR.STORAGE.DOWNLOAD-FAILURE.DETAIL
    post-error-message: SYSTEM.ERROR.STORAGE.UPLOAD-FAILURE.DETAIL
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB

#-----------------------------------
--- # Spring AutoDoc
#-----------------------------------
springdoc:
  api-docs:
    path: /oas
  swagger-ui:
    path: /swagger

#-----------------------------------
--- # L10n & i18n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
