#-----------------------------------
--- # Application
#-----------------------------------
spring:
  application:
    name: thesis-webrepo
server:
  port: ${PORT:9090}
  servlet:
    context-path: /api
--- ## File upload limit
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB

#-----------------------------------
--- # Database
#-----------------------------------
spring:
  jpa:
    open-in-view: false
  # h2:
  #   console:
  #     enabled: false

--- # PostgreSQL
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  ## Datasource
  datasource:
    url: jdbc:postgresql://ec2-34-236-94-53.compute-1.amazonaws.com:5432/d8rl4gr6gp1bc9
    username: 'sufyrhyjwjaxne'
    password: '513532d46c4919cdb6ade1685055b5dcd8c17f74010e8c71c35f0253855bd331'

# --- # H2 In-Memory
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: create-drop
#   ## Datasource
#   datasource:
#     url: jdbc:h2:mem:testdb
#     username: 's53kr_lm8a6r'
#     password: '$p@s5w0rD_s53k12x'

#-----------------------------------
--- # Security
#-----------------------------------
application:
  security:
    # DEFINE ROUNDS OF VALIDATION
    # TO STRENGTHEN PASSWORD PROCESSING
    strength: 16
    # DEFAULT LOGIN CREDENTIALS
    # WITH ROLE OF SYSTEM ADMIN
    default-login-enabled: true
    default-login: sysadm
    default-password: sysadm

#-----------------------------------
--- # Storage Service (MinIO)
#-----------------------------------
application:
  minio:
    url: cnurl
    username: uname
    password: paswd
