#-----------------------------------
--- # Application
#-----------------------------------
spring:
  application:
    name: thesis-webrepo
server:
  port: ${PORT}
  servlet:
    context-path: /api
--- ## File upload limit
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB

#-----------------------------------
--- # Database
#-----------------------------------
spring:
  jpa:
    open-in-view: false

--- # PostgreSQL
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  ## Datasource
  datasource:
    url: jdbc:${DATABASE_URL}

#-----------------------------------
--- # Security
#-----------------------------------
application:
  security:
    # DEFINE ROUNDS OF VALIDATION
    # TO STRENGTHEN PASSWORD PROCESSING
    strength: 8
    # DEFAULT LOGIN CREDENTIALS
    # WITH ROLE OF SYSTEM ADMIN
    default-login-enabled: true
    default-login: sysadm
    default-password: sysadm

#-----------------------------------
--- # Storage Service (MinIO)
#-----------------------------------
application:
  minio:
    url: cnurl
    username: uname
    password: paswd

#-----------------------------------
--- # Spring AutoDoc
#-----------------------------------
springdoc:
  api-docs:
    path: /oas
  swagger-ui:
    path: /swagger
