on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build project
      run: mvn -B package --file pom.xml
    - name: Save artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: executable
        path: ./target/*.jar
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Get artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: executable
        path: ./artifact/executable
    - name: Upload artifact to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./artifact/executable
        remote: /home/be
        host: 103.157.97.165
        username: root
        password: repository123
    - name: Run executable
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: service thesis-webrepo restart
        host: 103.157.97.165
        username: root
        password: repository123
